# To Run:
# >> docker-compose.exe up
# https://github.com/ppcamp/docker-postgres-uuid
version: '3.1'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${DATABASE}
    container_name: cpChallenge
    ports:
      - 5432:5432
